eureka:
  client:
    service-url:
      defaultZone: http://service-eureka:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${random.value}
    prefer-ip-address: true

resilience4j:
  circuitbreaker:
    configs:
      default:
        event-consumer-buffer-size: 10
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED
        slow-call-rate-threshold: 50
        slow-call-duration-threshold: 1s
        ignore-exceptions:
          - es.inetum.commons.exception.exceptions.BadRequestException 
          - es.inetum.commons.exception.exceptions.NotFoundException  
    instances:
      create: 
        base-config: default
      instance:
        base-config: default
  retry:
    instances:
      create:
        max-attempts: 3
        wait-duration: 10ms
        ignore-exceptions:
          - es.inetum.commons.exception.exceptions.BadRequestException
          - es.inetum.commons.exception.exceptions.NotFoundException
  ratelimiter:
    limiters:
      instance:
        limit-for-period: 10
        limit-refresh-period: 10s
        timeout-duration: 2s
  timelimiter:
    configs:
      default:
        timeout-duration: 2s
    instances:
      instance:
        base-config: default

spring:
  application:
    name: service-parameters
  datasource:
    url: jdbc:postgresql://ms-postgresql16:5432/ms_portanode_db
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        jdbc:
          lob:
            non-contextual-creation: true
  
logging:
  level:
    org:
      hibernate:
        SQL: debug

prueba:
  config: esta es una propiedad cambiada para probar el refresh desde docker